services:
  postgres:
    image: postgres:15-alpine
    container_name: momently-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: momently-redis
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/momently-backend:latest
    container_name: momently-backend
    restart: unless-stopped
  
    depends-on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  environment:
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    SPRING_DATASOURCE_URL: jdbc:posgresql://postgres:5432/${DB_NAME}
    SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    SPRING_REDIS_HOST: redis
    SPRING_REDIS_PORT: 6379

    JWT_SECRET: ${JWT_SECRET}
    JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

    ports:
      - "8080:8080"

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/momently-frontend:latest
    container_name: momently-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:8080"

  ai-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/momently-ai:latest
    container_name: momently-ai
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      BACKEND_URL: http://backend:8080
      ENVIRONMENT: production


    ports:
      - "8000:8000"

  volumes:
    postgres_data:
      name: momently-postgres-data

      
