server {
    # it listen for incoming requests on port 8080
    listen 8080;
    
    # the directory has compiled Angular files
    # HTML, CSS and Typescript are copied here by Dockerfile 
    root /usr/share/nginx/html;

    # default file 
    index index.html index.htm;

    # Handle all incoming requests
    location / {

        # below means: try to find the requested file , if it does not exists, serve index.html instead 
        try_files $uri $uri/ /index.html; # if the requested file does not exist, then it serve index.html
    }
}

# qwill later use nginx to acts a revere proxy so it can forwards requets to backend 