# to resolve the error found when running the docker build 
# unable to find the cache key which helps Docker to determine if it can use cached layers to help it to build faster 

server {

    listen 4200; # must match the port that is exposed in dockerfile 
    server_name localhost; # the name of this server -> (future): will later on change it to a the domain name 

    # root URL 
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm; # dekfault filename to open 
    }

    # this is the custom error page for internal server errors
    # this will redirect the user's browser to a generic error path 
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}