events {
    # a typical nginx file would have worker_connections 1024;
    # worker_connections 1024 is needed for high traffic site because this line increases the number of client connections that each worker process can handle 
    worker_connections 1024;
}

# anything related to HTTP traffic 
http {

    include       /etc/nginx/mime.types;
    default_type  application/octect-stream;

# the Reverse Proxy 
    server {
        # chnaged from 80 to 8080
        listen 8080;

        # will replace this with our domain name 
        server_name _;

        # Angular frontend
        location / {
            proxy_pass http://frontend:8080;

            # based on many files, this are lines that are standard production nginx.conf has 
            # link: https://github.com/keycloak/keycloak/discussions/12090

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;

        }

        # Spring Boot API 
        location /api/ {
            proxy_pass http://backend:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;

        }

        # FastAPI AI service 
        location /ai/ {
            proxy_pass http://ai-service:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;

        }



    }
}