# the problem faced was the container was running as unpriviledged nginx user, it cannot write to /run 
pid /tmp/nginx.pid;

events {
    # a typical nginx file would have worker_connections 1024;
    # worker_connections 1024 is needed for high traffic site because this line increases the number of client connections that each worker process can handle 
    worker_connections 1024;
}

# anything related to HTTP traffic 
http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # gzip compression to help with Angular build 
    # https://shape.host/resources/how-to-optimize-nginx-for-an-angular-application
    # https://medium.com/@piyalidas.it/angular-run-on-nginx-server-07b9b8682714

    # disable server version 
    # users will see nginx and not nginx
    server_tokens_off;

    gzip on;
        gzip_vary_on;
        gzip_comp_level_6;
        gzip_min_length 60;

        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/xml
            image/svg+sml;


# the Reverse Proxy 
    server {
        # chnaged from 80 to 8080
        listen 80;

        # will replace this with our domain name 
        server_name _;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Angular frontend
        location / {
            # based on many files, this are lines that are standard production nginx.conf has 
            # link: https://github.com/keycloak/keycloak/discussions/12090
            include /etc/nginx/proxy;
            proxy_pass http://frontend:8080;
        }

        # Spring Boot API 
        location /api/ {
            include /etc/nginx/proxy;
            proxy_pass http://backend:8080;
        }

        # so the backend endpoints expects /api because they all starts with /api 
        # but swagger, actuator and api-docs set in SecurityConfig don't so I will add locations for them her

        location /swagger-ui/ {
            proxy_pass http://backend:8080/swagger-ui/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # = means to exact match to get /v3/api-docs 
        # because on the browser, it adds an '/' at the end
        location = /v3/api-docs {
            proxy_pass http://backend:8080/v3/api-docs;
        }

        location /actuator/ {
            proxy_pass http://backend:8080/actuator/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # FastAPI AI service 
        location /ai/ {
            include /etc/nginx/proxy;
            proxy_pass http://ai-service:8000/;

            
        }

        # asssests cache

        location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf)$ {
            expires 30d;
            add_header Cache-Control "public, immutable"
            proxy_pass http://frontend:8080;
            include /etc/nginx/proxy;
        }



    }
}