#all the data needed here will come from the .env in the backend file path


#trying to debug the spring-dotenv
dotenv.enabled=true
dotenv.filename=.env
dotenv.system-properties=ALL
dotenv.prefix=ENV_

#DB configs
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always