#all the data needed here will come from the .env in the backend file path
# this tells spring-dotenv to load the .env file 

#trying to debug the spring-dotenv
dotenv.enabled=true
dotenv.filename=.env
dotenv.system-properties=ALL
# dotenv.prefix=ENV_
