# Below, it has all configs and need to change from YAML syntax 

# Spring Dotenv 

# This section loads environment variables from apps/backend/.env
# Please create your own .env file using .env.example as the template

dotenv.enabled=true
dotenv.filename=.env
dotenv.system-properties=ALL

# Application
spring.application.name=momently-backend

# Data source

# This is not using defaults so please create .env file 

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# spring.datasource.driver-class-name=org.postgresql.Driver - commented out because Spring Boot will automatically detects the driver 

# JPA / Hibernate

# This section ONLY validates schema 
# Database schema will maintain using Flyway migrations

spring.jpa.hibernate.ddl_auto=validate

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway

# This section will execute database migrations 
spring.flyway.enabled=true

# where the migration files are 
spring.flyway.locations=classpath:db/migration

# we used Flyway after the database was created 
spring.flyway.baseline-on-migrate=true

# validate the migration history first
spring.flyway.validate-on-migrate=true 

server.port=${SERVER_PORT:8080}

# JWT

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Google OAuth 
app.google.client-id=${GOOGLE_CLIENT_ID:dummy-client-id}
app.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy-client-secret}
app.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/api/integrations/google/calendar/callback}

# Github Oauth
app.github.client-id=${GITHUB_CLIENT_ID:dummy-client-id}
app.github.client-secret=${GITHUB_CLIENT_SECRET:dummy-client-secret}
app.github.redirect-uri=${GITHUB_REDIRECT_URI:http://localhost:8080/api/integrations/github/callback}

#AI service
app.ai-service.url=${AI_SERVICE_URL:http://localhost:8000}
ai.service.url=http://localhost:8000

# CORS configuration
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS}
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS}


#MFA configs 
app.mfa.issuer=${MFA_ISSUER:Timesheets AI}
app.mfa.max-login-attempts=${MFA_MAX_ATTEMPTS:5}
app.mfa.lock-duration-minutes=${MFA_LOCK_DURATION:30}
app.mfa.code-length=${MFA_CODE_LENGTH:6}

# Swagger

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.pretty-print=true

# Logging 
logging.level.timesheets=INFO
# logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO

#email configs
app.email.from=${BREVO_FROM_EMAIL: noreply@momently.com}
app.email.from-name=${BREVO_FROM_NAME: Momently}
app.base-url=${APP_BASE_URL: http://localhost:8080}

# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Actuator 
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always 

management.metrics.tags.application=momently

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:dummmy-bucket}
aws.access-key=${AWS_ACCESS_KEY_ID:dummy_id}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:dummy_key}


# redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
