# workflow configuration where it runs tests and etc for the ai
# [Stack: Python (FastAPI)]

# the trigger: this will run when there is a pull request or push on the main or dev branches
name: AI Pipeline

on:
  push:
    branches: [main, dev, dev2]
  pull_request: 
      branches: [main, dev]

jobs:
  ai-check:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

    # Logic Gate: this is used to determine where the changes occur and if it occurs in the ai service folder, therefore the ai-check should run otherwise passed quickly 
      - name: Check for AI Service Changes
        id: filter
        uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c
        continue-on-error: true
        with:
          filters: |
            ai:
              - 'ai-service/**'
              - '.github/workflows/ai-ci.yml'

      - name: Retry 
        if: steps.filter.outcome == 'failure'
        id: retry
        uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c
        with:
          filters: |
              ai:
                  - 'ai-service/**'
                  - '.github/workflows/ai-ci.yml'

#===================== BUILD stage ================================

    # Set up the required Python environment for this workflow 
      - name: Set up Python 
        if: steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true'
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.12'
          cache: 'pip' 
          # the cache will be invalid and destroyed when the textfil e
          cache-dependency-path: ai-service/requirements.txt

      - name: Install Dependencies 
        if: steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true'
        run: |
          cd ai-service 
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

#===================== PLAN stage ================================

        # ruff is recommended for Python FastAPI (made by Astral) 
        # it is fast and it ahndles linting, auto fix sytnax and formatting so no need for different kinds of tools 
      - name: Run Ruff Lint 
        if: steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true'
        run: |
          cd ai-service
          ruff format --check .
          ruff check .

#===================== TEST stage ================================

      - name: Run Tests 
        if: steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true'
        working-directory: ai-service
        env:
          PYTHONPATH: .
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          pytest
#==================== Login to AWS  ===========================================================
      - name: Configure AWS Credentials
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        uses: aws-actions/configure-aws-credentials@d0834ad3a60a024346910e522a81b0002bd37fea
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

#==================== Login to AWS ECR  ===========================================================
      - name: Login to AWS ECR
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev2' || github.ref == 'refs/heads/main') && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@33f92af657bba1882ab79d8621debd2f6769a0c9

#===================== RELEASE stage ================================

        # ensure that the docker image is built successfully and that it can be containerized and deployed 
        # github sha - so every build image created, it will be associated with a hash (commit number) - which will helps us to know which commit created an image
      - name: Build Docker Image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev2' || github.ref == 'refs/heads/main') && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        working-directory: ai-service
        run: |
          docker build -t momently-ai:${{ github.sha}} .

#====================== SECURITY scan ================================
      - name: Scan Docker Image
        if: github.event_name == 'push' && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: momently-ai:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL

#====================== Tag Image ====================================

        # docker tag is giving same image another name 
        # latest - give us the newest version and aws ec2 instance will run this to get latest version 
      - name: Tag Docker Image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev2' || github.ref == 'refs/heads/main') && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        run: |
          docker tag momently-ai:${{ github.sha }} ${{ steps.login-to-ecr.outputs.registry }}/momently-ai:latest
          docker tag momently-ai:${{ github.sha }} ${{ steps.login-to-ecr.outputs.registry }}/momently-ai:${{ github.sha }}

#====================== Push to ECR ======================
      
      - name: Push Docker Image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev2'|| github.ref == 'refs/heads/main') && (steps.filter.outputs.ai == 'true' || steps.retry.outputs.ai == 'true')
        run: |
          docker push ${{ steps.login-to-ecr.outputs.registry }}/momently-ai:latest
          docker push ${{ steps.login-to-ecr.outputs.registry }}/momently-ai:${{ github.sha }}