# workflow configuration where it automatically runs tests for the backend
name: Backend Pipeline 

# the trigger - when pull request and push is created on those branches only 

on:
    push:
        branches: [main, dev]
        # paths:
        #     - 'apps/backend/**' 
    pull_request:
        branches: [main, dev]
        # paths:
        #     - 'apps/backend/**'

jobs:
    # this is only for backend check only and provide job access to the code in the repo 
    # ubuntu latest - Github will uses linux machine - better and minimize build minutes
    backend-check:
        runs-on: ubuntu-latest

        permissions:
          contents: read

        steps:
        # Note here: check if we use checkout@sha - that was in lecture slides not v4 (could be more secure)
        - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

        # Logic Gate: This is used to determine if the files changed are in Backend
        # dorny repo is used in this logic gate - this is using SHA instead of versions for security suggested by SonarQube 
        # The SHA is version 3 (v3.0.3)
        - name: Check for Backend Changes
          id: filter
          uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c 
          continue-on-error: true
          with:
            filters: |
                backend:
                 - 'apps/backend/**'
                 - '.github/workflows/backend-ci.yml'

        - name: Retry 
          if: steps.filter.outcome == 'failure' 
          id: retry
          uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c
          with:
            filters: |
                backend:
                    - 'apps/backend/**'
                    - '.github/workflows/backend-ci.yml'

#===================== BUILD stage ================================
       
        # Only runs if backend changes 
        - name: Set up JDK 17
          if: steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true'
          uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
          with:
            # these lines tell Github Actions which installer and distribution to install
            java-version: '17'
            distribution: 'temurin'
            # maven (pom.xml) will be used to download dependencies and it will be cache so it will spped up with the builds
            cache: 'maven'
            cache-dependency-path: apps/backend/pom.xml

#===================== PLAN, BUILD & TEST stage ================================
          # clean verify does all 3 stages 
        - name: Build with Maven 
          if: steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true'
          run: mvn -f apps/backend/pom.xml clean verify 

#==================== Login to AWS  ===========================================================
        - name: Configure AWS Credentials
          if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true')
          uses: aws-actions/configure-aws-credentials@d0834ad3a60a024346910e522a81b0002bd37fea
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

#==================== Login to AWS ECR  ===========================================================
        - name: Login to AWS ECR
          if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true')
          id: login-to-ecr
          uses: aws-actions/amazon-ecr-login@33f92af657bba1882ab79d8621debd2f6769a0c9

#===================== RELEASE stage ================================

        # ensure that the docker image is built successfully and that it can be containerized and deployed 
        # github sha - so every build image created, it will be associated with a hash (commit number) - which will helps us to know which commit created an image
        - name: Build Docker Image
          if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true')
          working-directory: apps/backend
          run: docker build -t momently-backend:${{ github.sha}} .

        # docker has image locally
        #  so example: momently-backend:544dr55645
        # ecr DOES NOT have this image - only Github runner knows


#====================== SECURITY scan ================================
        - name: Scan Docker Image
          if: github.event_name == 'push' && (steps.filter.outputs.frontend == 'true' || steps.retry.outputs.frontend == 'true')
          uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
          with:
            image-ref: momently-frontend:${{ github.sha }}
            format: table
            exit-code: 1
            ignore-unfixed: true
            severity: CRITICAL
        
#====================== Tag Image ====================================

        # docker tag is giving same image another name 
        # latest - give us the newest version and aws ec2 instance will run this to get latest version 
        - name: Tag Docker Image
          if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true')
          run: |
            docker tag momently-backend:${{ github.sha }} ${{ steps.login-to-ecr.outputs.registry }}/momently-backend:latest
            docker tag momently-backend:${{ github.sha }} ${{ steps.login-to-ecr.outputs.registry }}/momently-backend:${{ github.sha }}

#====================== Push to ECR ======================
        - name: Push Docker Image
          if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && (steps.filter.outputs.backend == 'true' || steps.retry.outputs.backend == 'true')
          run: |
            docker push ${{ steps.login-to-ecr.outputs.registry }}/momently-backend:latest
            docker push ${{ steps.login-to-ecr.outputs.registry }}/momently-backend:${{ github.sha }}